### ISSUE TITLE
I can't download message

### ISSUE THREAD

**Issue by mapols** [proshunsuke/colmsg#112]
It was working well until yesterday.
This morning I updated the Nogizaka message application.
Then the problem has started.

I get this error message.
[31m[colmsg error][0m: HTTP status client error (400 Bad Request) for url (https://api.n46.glastonr.net/v2/groups?)

I am an appstore user. I use Windows 10.
I was using ver 3.1.1. until yesterday, and I got the the error message above, so I updated to new verseion (3.2.1.) a while ago and tried again, but I'm still getting the same error message.
How can I hold this problem?

**Comment by proshunsuke** [comment]
related to https://github.com/proshunsuke/colmsg/issues/109
