### ISSUE TITLE
Can't Download Hinatazaka 1st gen's message

### ISSUE THREAD

**Issue by bodarycomforts** [proshunsuke/colmsg#25]
### Description

Hi, I can't download Hinatazaka 1st gen's message. 

### Reproduction steps

PS C:\Users\Orions\colmsg-0.1.2> C:\Users\Orions\colmsg.exe -n 影山優佳 --username <my Username> --token <my Token>

### Log output
https://pastebin.com/raw/whRcGYAK

**Comment by proshunsuke** [comment]
@bodarycomforts 
Thank you for reporting.
I fixed, and released v0.1.3. Please retry.
