### ISSUE TITLE
Can't download messages from previous refresh token

### ISSUE THREAD

**Issue by bodarycomforts** [proshunsuke/colmsg#32]
first, i used my refresh token like"7fac6109-....." on my computer 
and then i used friend's refresh token "40ef2f64-......".
But when i come back to use my refresh token. program was download data from friend's refresh token.
i tried to restart computer , it wasn't solve my problem

**Comment by proshunsuke** [comment]
@bodarycomforts  
Sorry for the late response.

Please tell me following questions:

* Are you still in trouble with this problem?
* The version of colmsg you are using
* Please show your colmsg config directory. like this.
  * ```shell
    tail ~/.config/colmsg/*
    ```
  * It's sensitive data, so you don't have to show everything
* After you faced this problem, did you get your refresh token again?

**Comment by proshunsuke** [comment]
close issue for v2.0.0 released.
https://github.com/proshunsuke/colmsg/issues/33#issuecomment-728220319
