### ISSUE TITLE
レターを送れたメンバーはエーラー出る

### ISSUE THREAD

**Issue by teddy8997** [proshunsuke/colmsg#41]
エーラーログは下のリンクです。
https://drive.google.com/file/d/1FmcN8dQ-mR7J3liLnQGlWnqzZXrKKMiI/view?usp=sharing

**Comment by proshunsuke** [comment]
Thanks for the issue. I try to fix it.

**Comment by proshunsuke** [comment]
fix and released v2.0.1.

**Comment by proshunsuke** [comment]
@teddy8997 fix and released v2.0.1.

**Comment by teddy8997** [comment]
@proshunsuke Thanks for fix the bug. I try to use the new version v2.0.1, but there is another problem.
the problem logs is at the link: https://drive.google.com/file/d/1xmhNyXs1eKsuhA4A8-SWGXGIjEUC_h45/view?usp=sharing
I have been tried two computer with two different networks ,but there are same problems.

**Comment by proshunsuke** [comment]
sorry. I try to fix again.

**Comment by proshunsuke** [comment]
@teddy8997 
I released v2.0.2. Please try again.
https://github.com/proshunsuke/colmsg/releases/tag/v2.0.2

**Comment by teddy8997** [comment]
@proshunsuke Thanks for you to fix the problem. I have tried version 2.0.2 this morning, but there is same problem. the messages of hinatazaka46 can't download and the messages of sakurazaka46 can. I also tried to use two computer under different network, there are same problem. The picture is at link: https://drive.google.com/file/d/1_sBJSufFhF8CvBoHhtR14o5OXpXp8hZL/view?usp=sharing

**Comment by proshunsuke** [comment]
@teddy8997 

please use `-g` option, and try again.

```bash
colmsg --h_refresh_token token -g hinatazaka -n 小坂菜緒
```

**Comment by teddy8997** [comment]
@proshunsuke ありがとうございます。おかげさまで保存出来ました！このツールは本当に便利です。proshunsuke さんは凄すぎ
る。2020年はもうすぐ終わりました。ここでよいお年を。
