### ISSUE TITLE
unwrap時のエラー

### ISSUE THREAD

**Issue by ustr0aTe** [proshunsuke/colmsg#49]
遅れたけど、あけおめ！
わたしは日本語があまりよくないので、理解されないかもしれない。

そのエラーは2.0verときからもあっている。
一部分のメンバーのidとかdateとか中のparameter違いがある、splitかunwrapときに例外處理のことがしなくて、エラーがあった...(?)
全員購読入していないから、全員のDEBUGログができない。ごめんなさい。
ログ写真を付き
![2021-01-01_230115_cened](https://user-images.githubusercontent.com/67262252/103443254-4584c080-4c98-11eb-8cb4-cfab217313f2.png)

**Comment by proshunsuke** [comment]
Thanks for the issue

**Comment by ustr0aTe** [comment]
Sorry for the issue.
I just figure out the issue may occurred by my PC setting.
This tool actually is working fine in my MacBook pro and other windows PC.
Then, I did some tests and found the issue only happened when the old path parameter "--dir D:\user\colmsg" existing (the path used since version.1.0).
Once I change the path, the tool working again.
although at the last I still don't know how this problem occur because of not all member giving error, seem there are no more issue.
Thanks for the tool.

**Comment by proshunsuke** [comment]
Thanks for your comment. I'm glad the tool works correctly.

**Comment by ustr0aTe** [comment]
Just an update.
In conclude, this problem occurred because I put some other files in their folder. 
And I think problem occurred by when the tool check file exist in a directory or not, it get the name (?) in the folder for checking and comparer with the data the tool obtain from the server.
Therefore the issue come up if the folder have a file name not in pattern "_"(unwarp() error) or the file name too long (OverFlow error)
So.... don't put other files in subfolder.
