### ISSUE TITLE
アップリの最新バージョン2.1.02リリースした、ツールは使い出来なくなりました。

### ISSUE THREAD

**Issue by teddy8997** [proshunsuke/colmsg#50]
今使いツールバージョンは2.0.2です。
エラーログはリンクで
https://drive.google.com/file/d/1LVCHSQyJURKpz6TcsJjIQXKEs6B2Tzoy/view?usp=sharing

**Comment by ustr0aTe** [comment]
client.rs 中の164列、
` "jp.co.sonymusic.communication.keyakizaka 2.1".to_string(),` -> ` "jp.co.sonymusic.communication.keyakizaka 2.2".to_string(),`
2.1から2.2に変更する。
そして`cargo build`

**Comment by proshunsuke** [comment]
Thanks. I released v2.0.3.

**Comment by teddy8997** [comment]
わざわざすみません。
ありがとうございます。昨日僕は2.1から2.2を変更しました、そしてcargo buildしました。使いできます！　もう一つの疑問があります、例えば僕のtokenはA、友達1のtokenはB、友達2のtokenはC、まずcolmsg --h_refresh-token A -- dir D:\xx -g hinatazaka を入力した、completeあと、colmsg --h_refresh-token B -- dir D:\xx -g hinatazaka  を入力した、completeあと、colmsg --h_refresh-token C -- dir D:\xx -g hinatazaka  を入力した。なぜBとCの購読downloadできないです。BとCの実施結果はAの購読downloadです🤔

**Comment by proshunsuke** [comment]
> BとCの実施結果はAの購読downloadです

Sorry... I couldn't understand this sentence.
Can you explain in more detail?

**Comment by teddy8997** [comment]
I use the token A to download the A's subscription messages (hinatazaka). After complete download, I use the token B to download  B's subscription messages(hinatazaka), but the program didn't download B's subscription messages, it download A's subscription messages. For example, if token A's subscription member is 加藤史帆 and 金村美玖. when downloading CMD message appears

colmsg --h_refresh_token A --dir D:\osushi -g hinatazaka
saving messages of 加藤史帆...
complete saving messages of 加藤史帆!
saving messages of 金村美玖..
complete saving messages of 金村美玖!

then token B's  subscription member is 齊藤京子 and 富田鈴花. I use token B to download message.  CMD message appears

colmsg --h_refresh_token B --dir D:\osushi -g hinatazaka
saving messages of 加藤史帆...
complete saving messages of 加藤史帆!
saving messages of 金村美玖..
complete saving messages of 金村美玖!

it doesn't download  B's  subscription member. It download A's subscription member.

I'm not sure it is a bug or not. I'm sorry for bothering you so much time.

**Comment by ustr0aTe** [comment]
> I use the token A to download the A's subscription messages (hinatazaka). After complete download, I use the token B to download B's subscription messages(hinatazaka), but the program didn't download B's subscription messages, it download A's subscription messages. For example, if token A's subscription member is 加藤史帆 and 金村美玖. when downloading CMD message appears
> 
> colmsg --h_refresh_token A --dir D:\osushi -g hinatazaka
> saving messages of 加藤史帆...
> complete saving messages of 加藤史帆!
> saving messages of 金村美玖..
> complete saving messages of 金村美玖!
> 
> then token B's subscription member is 齊藤京子 and 富田鈴花. I use token B to download message. CMD message appears
> 
> colmsg --h_refresh_token B --dir D:\osushi -g hinatazaka
> saving messages of 加藤史帆...
> complete saving messages of 加藤史帆!
> saving messages of 金村美玖..
> complete saving messages of 金村美玖!
> 
> it doesn't download B's subscription member. It download A's subscription member.
> 
> I'm not sure it is a bug or not. I'm sorry for bothering you so much time.

Which version are you using? 
Seem it related to the config file.
_OR Maybe your friends changed their Oshimen but not telling you._

**Comment by teddy8997** [comment]
When I use version 2.0.0 there is no this problem. Since version 2.0.2, this problem appears. I use version 2.0.3 now. 
I'm sure my friends are still subscript members. Is there any solution for this problem? Thank you for your reply.

**Comment by teddy8997** [comment]
I think I find why this situation occurs. In path colmsg -- config-dir, when finishes download token A, the file access_token doesn't delete. So when I download token B, it continues to use  token A's access_token file. When I manual delete the token A's access_token file after downloading token A, then run token B then result is right.
