### ISSUE TITLE
can't download message

### ISSUE THREAD

**Issue by bodarycomforts** [proshunsuke/colmsg#60]
C:\Users...\colmsg.exe -n 関有美子 --dir G:\colmsg --h_refresh_token <h_refresh_token> --s_refresh_token <s_refresh_token>

saving messages of 関有美子...
←31m[colmsg error]←[0: error: missing field `member_id` at line 1 column 1538, request url:

**Comment by proshunsuke** [comment]
Did you receive any other error messages?

**Comment by proshunsuke** [comment]
Which version are you using?

**Comment by bodarycomforts** [comment]
ver 2.0.3 
should i update to 2.0.4

**Comment by proshunsuke** [comment]
This issue may have been fixed in https://github.com/proshunsuke/colmsg/issues/54 .
