### ISSUE TITLE
Bad Request update_token

### ISSUE THREAD

**Issue by kanmipro** [proshunsuke/colmsg#61]
An error occurs when executing a command(.\colmsg.exe).

[Details]
 - colmsg:v2.0.4
 - config:--h_refresh_token {refresh_token} -g hinatazaka -d {downlod_dir}
 
HTTP status client error (400 Bad Request) for url (https://api.kh.glastonr.net/v2/update_token)

**Comment by proshunsuke** [comment]
The refresh_token may be wrong, please check it.

**Comment by kanmipro** [comment]
It seemed that the conf file had not been read.
Running the command without using the conf file in the default directory was successful.

Thanks.
