### ISSUE TITLE
日向坂しか購読していないとき

### ISSUE THREAD

**Issue by cruller0704** [proshunsuke/colmsg#63]
日向坂しか購読していないと-g hinatazakaつけないと以下のエラーが出るのはバグな気がします。
[colmsg error]: HTTP status client error (400 Bad Request) for url (https://api.s46.glastonr.net/v2/update_token)

**Comment by proshunsuke** [comment]
報告ありがとうございます。
しかし現在それは仕様となっています。

**Comment by cruller0704** [comment]
了解です。
