### ISSUE TITLE
thread 'main' panicked

### ISSUE THREAD

**Issue by bodarycomforts** [proshunsuke/colmsg#71]
I have problem when download 宮田愛萌

saving messages of 宮田愛萌...
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/message/saver.rs:220:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by proshunsuke** [comment]
sorry, I just noticed. I'll investigate.

**Comment by proshunsuke** [comment]
Does the same problem occur if you download it from the beginning, for example by using the -d option?

```
colmsg -d path/to/another/dir -n 宮田愛萌
```

**Comment by proshunsuke** [comment]
No reply, so I'll close.
Please open again if you encounter same problem.
