### ISSUE TITLE
can't download 渡邉美穂

### ISSUE THREAD

**Issue by alivealife** [proshunsuke/colmsg#75]
Only when use colmsg.exe -n 渡邉美穂 will nothing happened

**Comment by proshunsuke** [comment]
Error message, please.

**Comment by alivealife** [comment]
There is no error message,just nothing happened

**Comment by proshunsuke** [comment]
Please tell following

* length of subscription
* result of executing without options
* how to specify h_refresh_token

**Comment by alivealife** [comment]
I'm sorry to waste your time.
I try it again today,and it's worked.

**Comment by proshunsuke** [comment]
Oh, that's good to know.
