### ISSUE TITLE
(400 Bad Request) for update_token

### ISSUE THREAD

**Issue by limangox** [proshunsuke/colmsg#92]
APP's UA and App-ID have been updated, please follow up, otherwise there will be 400 Bad Request.Thanks

**Comment by proshunsuke** [comment]
Thank you for the issue.
I might be able to address it within the next 2-3 days.
If anyone knows the UA and App-ID offhand, please let me know.

**Comment by limangox** [comment]
齋藤飛鳥メッセージ:
    'x-talk-app-id': 'jp.co.sonymusic.communication.asukasaito 2.3',
    'user-agent': 'Hot/1.1.01 (jp.co.sonymusic.communication.asukasaito; build:169; iOS 16.3.1) Alamofire/5.6.2',

乃木坂46メッセージ:
    'x-talk-app-id': 'jp.co.sonymusic.communication.nogizaka 2.3',
    'user-agent': 'Hot/1.8.01 (jp.co.sonymusic.communication.nogizaka; build:169; iOS 16.3.1) Alamofire/5.6.2',

**Comment by limangox** [comment]
> Thank you for the issue. I might be able to address it within the next 2-3 days. If anyone knows the UA and App-ID offhand, please let me know.

齋藤飛鳥メッセージ:
'x-talk-app-id': 'jp.co.sonymusic.communication.asukasaito 2.3',
'user-agent': 'Hot/1.1.01 (jp.co.sonymusic.communication.asukasaito; build:169; iOS 16.3.1) Alamofire/5.6.2',

乃木坂46メッセージ:
'x-talk-app-id': 'jp.co.sonymusic.communication.nogizaka 2.3',
'user-agent': 'Hot/1.8.01 (jp.co.sonymusic.communication.nogizaka; build:169; iOS 16.3.1) Alamofire/5.6.2',

**Comment by AcD08** [comment]
I got same error message in 日向坂46メッセージ too

**Comment by proshunsuke** [comment]
Released v3.1.1
https://github.com/proshunsuke/colmsg/releases/tag/v3.1.1
