### ISSUE TITLE
HTTP status client error (400 Bad Request) for url

### ISSUE THREAD

**Issue by hongbre** [proshunsuke/colmsg#97]
An error occurred after Sakurazaka's 3rd generation message started.

> [colmsg error]: HTTP status client error (400 Bad Request) for url (https://api.s46.glastonr.net/v2/update_token)

**Comment by proshunsuke** [comment]
Are there similar errors in other members' messages?

**Comment by hongbre** [comment]
櫻坂の他のメンバーも同じでした。今乃木坂と日向坂はサブスクしていないので確認できませんでした。私のrefresh keyも確認してみます。

**Comment by AzureOSK** [comment]
I have a similar issue for the new "colmsg\キャンペーン\新参者櫻坂46三期生" folder:
![Untitled](https://github.com/proshunsuke/colmsg/assets/35568697/db052d08-6919-45ca-b8dc-afa99929e096)

No issues for Hinatazaka and Nogizaka messages.

**Comment by hongbre** [comment]
> Are there similar errors in other members' messages?

私のrefresh tokenが変わりました。すみません。
